# [Beginner] - Numpy Basic Tutorial


How to use this notebook :

There is only minimum explanation

This notebook could be helpful for who want to see how code works right away

<HR>


In [1]:
# linear algebra
import numpy as np 

# data processing, CSV file I/O (e.g. pd.read_csv)
import pandas as pd 

In [2]:
a = np.array([1, 2, 3])
b = np.array([(1,2,3), (4,5,6)])

print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


## 1. Ndarray function
<HR>

* **ndarray.ndim :** the dimension number of the array
* **ndarray.shape :** the dimension of the array, n rows and m columns is n,m
* **ndarray.size :** the number of all elements in the array
* **ndarray.dtype :** the type of the element in the array, such as int32, float64
* **ndarray.itemsize :** the size of each element in the array, in bytes
* **ndarray.data :** the buffering for storing the array elements

In [3]:
print('a=')
print(a)
print("a's ndim :",a.ndim)
print("a's shape :",a.shape)
print("a's size :",a.size)
print("a's dtype :",a.dtype)
print("a's itemsize :",a.itemsize)

print('')

print('b=')
print(b)
print("b's ndim :",b.ndim)
print("b's shape :",b.shape)
print("b's size :",b.size)
print("b's dtype :",b.dtype)
print("b's itemsize :",b.itemsize)

a=
[1 2 3]
a's ndim : 1
a's shape : (3,)
a's size : 3
a's dtype : int64
a's itemsize : 8

b=
[[1 2 3]
 [4 5 6]]
b's ndim : 2
b's shape : (2, 3)
b's size : 6
b's dtype : int64
b's itemsize : 8



## 2. Create a specific array
<HR>
    
* **zeros :** create an array whose elements are all 0
* **ones :** create an array whose elements are all 1
* **empty :** create uninitialized data. so the content is undefined.
* **arange :** create an array by specifying the scope and step-length
* **linespace :** create an array by specifying the range and the number of elements
* **random :** generate random numbers

In [4]:
a = np.zeros((2,3))
print('np.zeros((2,3) :\n',a)
print('\n')
b = np.ones((2,3))
print('np.ones((2,3)) :\n',b)
print('\n')
c = np.empty((2,3))
print('np.empty((2,3)) :\n',c)
print('\n')
d = np.arange(1, 2, 0.3)    # 0.3 means gap
print('np.arange(1, 2, 0.3):\n',d)
print('\n')
e = np.linspace(1, 2, 7)    # 7 means how many
print('np.linspace(1, 2, 7) :\n',e)
print('\n')
f = np.random.random((2,3))
print('np.random.random((2,3)) :\n',f)

np.zeros((2,3) :
 [[0. 0. 0.]
 [0. 0. 0.]]


np.ones((2,3)) :
 [[1. 1. 1.]
 [1. 1. 1.]]


np.empty((2,3)) :
 [[1. 1. 1.]
 [1. 1. 1.]]


np.arange(1, 2, 0.3):
 [1.  1.3 1.6 1.9]


np.linspace(1, 2, 7) :
 [1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.        ]


np.random.random((2,3)) :
 [[0.25256187 0.59014604 0.69543674]
 [0.94722945 0.40656084 0.82981093]]


## 3. Shape and operation
<HR>

* **reshape :** generate a new array based on the existing array 
* **vstack :** stack multiple arrays in vertical direction
* **hstack :** stack multiple arrays in horizontal direction
* **hsplit :** split the array horizontally
* **vsplit :** split the array vertically

### reshape

In [5]:
a = np.arange(11, 20)
print(a)
print('\n')


# -1 means automatically
a = a.reshape(3, -1)
print(a)

[11 12 13 14 15 16 17 18 19]


[[11 12 13]
 [14 15 16]
 [17 18 19]]


### vstack

In [6]:
a = np.array([(1,2,3), (4,5,6)])
print('a :\n',a)
print('\n')

b = np.arange(11, 20)
b = b.reshape((3,-1))
print('b :\n',b)


a :
 [[1 2 3]
 [4 5 6]]


b :
 [[11 12 13]
 [14 15 16]
 [17 18 19]]


In [7]:
c = np.vstack((a, b))
print("c :\n",c)

c :
 [[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


### hstack

In [8]:
a = a.reshape(3,2)
print('a :\n',a)
print('\n')
print('b :\n',b)

a :
 [[1 2]
 [3 4]
 [5 6]]


b :
 [[11 12 13]
 [14 15 16]
 [17 18 19]]


In [9]:
d = np.hstack((a,b))
print("d :\n",d)

d :
 [[ 1  2 11 12 13]
 [ 3  4 14 15 16]
 [ 5  6 17 18 19]]


### hsplit

In [10]:
e = np.hsplit(d, 5) # Split a into 5
print("e :\n",e)

e :
 [array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([[11],
       [14],
       [17]]), array([[12],
       [15],
       [18]]), array([[13],
       [16],
       [19]])]


### vsplit

In [11]:
g = np.vsplit(d, 3)
print("g :\n",g)


g :
 [array([[ 1,  2, 11, 12, 13]]), array([[ 3,  4, 14, 15, 16]]), array([[ 5,  6, 17, 18, 19]])]


In [12]:
print(g[0])
print(g[1])
print(g[2])

[[ 1  2 11 12 13]]
[[ 3  4 14 15 16]]
[[ 5  6 17 18 19]]


## 4. Index
<HR>

In [13]:
# This is usual index in single dimension

base_data = np.arange(100, 200)
print("base_data :\n",base_data)

print("base_data[10] :\n",base_data[10]) 

base_data :
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]
base_data[10] :
 110


In [14]:
base_data2 = base_data.reshape(10, -1)
print("base_data2 :\n",base_data2)

base_data2 :
 [[100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]


In [15]:
# This is usual index in multiple dimention

print("base_data2[2] :\n",base_data2[2])
print("base_data2[2, 3] :\n",base_data2[2, 3])
print("base_data2[-1, -1] :\n",base_data2[-1, -1])

base_data2[2] :
 [120 121 122 123 124 125 126 127 128 129]
base_data2[2, 3] :
 123
base_data2[-1, -1] :
 199


In [16]:
# This is numpy index

every_five = np.arange(0, 100, 5)
print("base_data[every_five] :\n",base_data[every_five]) # we can put nparray as index


base_data[every_five] :
 [100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185
 190 195]


In [17]:
# This is numpy index

a = np.array([(1,2), (10,20)])
print("a :\n",a)
print("base_data[a] :\n",base_data[a])

a :
 [[ 1  2]
 [10 20]]
base_data[a] :
 [[101 102]
 [110 120]]


## 5. Mathematics
<HR>

In [18]:
base_data = (np.random.random((5, 5)) - 0.5) * 100 # random values in (0~1), So -0.5 makes negative, *100 makes (-50~50)
print("base_data :\n",base_data)
print('\n')
print('\n')
print('\n')
print("np.amin(base_data) :",np.amin(base_data)) # minimum
print('\n')
print("np.amax(base_data) :",np.amax(base_data)) # maximum
print('\n')
print("np.average(base_data) :",np.average(base_data)) # average
print('\n')
print("np.sum(base_data) :",np.sum(base_data)) # sum
print('\n')
print("np.sin(base_data) :\n",np.sin(base_data)) # trigonometric

base_data :
 [[-47.37358914  43.05665751  -8.01401311 -47.51953896 -33.73957878]
 [  8.11759541 -15.3577967  -19.72132879  40.51680225  32.67193153]
 [-18.7501255   46.99148948   0.68850922 -43.45685166 -46.31867274]
 [ 11.33343388 -10.1636808  -16.90275188  -5.50630738  30.73912355]
 [-24.45651033  -1.35429392  33.03810492 -42.45172832 -47.94544409]]






np.amin(base_data) : -47.9454440851134


np.amax(base_data) : 46.991489475306246


np.average(base_data) : -7.275142573683922


np.sum(base_data) : -181.87856434209806


np.sin(base_data) :
 [[ 0.24711263 -0.79900556 -0.98722227  0.38540727 -0.72973919]
 [ 0.96545464 -0.34305427 -0.76547093  0.31826831  0.95086101]
 [ 0.09926667  0.13201384  0.63538672  0.50159845 -0.72098108]
 [-0.9434663   0.67347729  0.93013805  0.70105647 -0.62630391]
 [ 0.62585781 -0.97665476  0.99868023  0.99919098  0.73220531]]


In [19]:
arr = np.arange(1,20)
print('arr :',arr)
arr = arr * arr              #Multiplies each element by itself 
print("Multpiles : ",arr)
arr = arr - arr              #Subtracts each element from itself
print("Substracts : ",arr)
arr = np.arange(1,20)
arr = arr + arr              #Adds each element to itself
print("Add : ",arr)
arr = arr / arr              #Divides each element by itself
print("Divide : ",arr)
arr = np.arange(1,20)
arr = arr + 50
print("Add +50 : ",arr)

arr : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Multpiles :  [  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361]
Substracts :  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Add :  [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
Divide :  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Add +50 :  [51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [20]:
print("Sqrt: ",np.sqrt(arr))   #Returns the square root of each element 
print("Exp: ",np.exp(arr))     #Returns the exponentials of each element
print("Sin: ",np.sin(arr))     #Returns the sin of each element
print("Cos: ",np.cos(arr))     #Returns the cosine of each element
print("Log: ",np.log(arr))     #Returns the logarithm of each element
print("Sum: ",np.sum(arr))     #Returns the sum total of elements in the array
print("Std: ",np.std(arr))     #Returns the standard deviation of in the array

Sqrt:  [7.14142843 7.21110255 7.28010989 7.34846923 7.41619849 7.48331477
 7.54983444 7.61577311 7.68114575 7.74596669 7.81024968 7.87400787
 7.93725393 8.         8.06225775 8.1240384  8.18535277 8.24621125
 8.30662386]
Exp:  [1.40934908e+22 3.83100800e+22 1.04137594e+23 2.83075330e+23
 7.69478527e+23 2.09165950e+24 5.68572000e+24 1.54553894e+25
 4.20121040e+25 1.14200739e+26 3.10429794e+26 8.43835667e+26
 2.29378316e+27 6.23514908e+27 1.69488924e+28 4.60718663e+28
 1.25236317e+29 3.40427605e+29 9.25378173e+29]
Sin:  [ 0.67022918  0.98662759  0.39592515 -0.55878905 -0.99975517 -0.521551
  0.43616476  0.99287265  0.63673801 -0.30481062 -0.96611777 -0.7391807
  0.1673557   0.92002604  0.82682868 -0.02655115 -0.85551998 -0.89792768
 -0.11478481]
Cos:  [ 0.7421542  -0.16299078 -0.91828279 -0.82930983  0.02212676  0.85322011
  0.89986683  0.11918014 -0.77108022 -0.95241298 -0.25810164  0.67350716
  0.98589658  0.39185723 -0.56245385 -0.99964746 -0.5177698   0.44014302
  0.99339038]
Log:  [

## 6. Matrix
<HR>

In [21]:
base_data = np.floor((np.random.random((5, 5)) - 0.5) * 100) # floor function is descending
print("base_data :\n",base_data)
print("\n")
print("base_data.T :\n",base_data.T)       # T means Transpose
print("base_data.transpose() :\n",base_data.transpose())
print("\n")
matrix_one = np.ones((5, 5))
print("matrix_one :\n",matrix_one)
print("\n")
minus_one = np.dot(matrix_one, -1) # dot function is multipy
print("minus_one :\n",minus_one)
print("np.dot(base_data, minus_one) :\n",np.dot(base_data, minus_one))

base_data :
 [[ -9. -12. -35. -14. -35.]
 [-49.   3.  39.   6.   9.]
 [-33. -40.   5. -43. -13.]
 [  2.  -4. -48.  31. -44.]
 [ 37.  -1. -24.  -4.  -8.]]


base_data.T :
 [[ -9. -49. -33.   2.  37.]
 [-12.   3. -40.  -4.  -1.]
 [-35.  39.   5. -48. -24.]
 [-14.   6. -43.  31.  -4.]
 [-35.   9. -13. -44.  -8.]]
base_data.transpose() :
 [[ -9. -49. -33.   2.  37.]
 [-12.   3. -40.  -4.  -1.]
 [-35.  39.   5. -48. -24.]
 [-14.   6. -43.  31.  -4.]
 [-35.   9. -13. -44.  -8.]]


matrix_one :
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


minus_one :
 [[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]]
np.dot(base_data, minus_one) :
 [[105. 105. 105. 105. 105.]
 [ -8.  -8.  -8.  -8.  -8.]
 [124. 124. 124. 124. 124.]
 [ 63.  63.  63.  63.  63.]
 [  0.   0.   0.   0.   0.]]


## 7. Random Number

In [22]:
print("random :\n",np.random.random(20)); # random numbers are between 0.0 ~ 1.0

print("rand :\n",np.random.rand(3, 4)); # rand function makes specified shape

print("randint :\n",np.random.randint(0, 100, 20)); # we can make specified range

print("permutation :\n",np.random.permutation(np.arange(20))); # disorder

random :
 [0.50066025 0.57670265 0.86052304 0.13525801 0.44125741 0.68464687
 0.36513901 0.19127523 0.27071564 0.18702844 0.79535844 0.88014615
 0.65229383 0.06089206 0.66412353 0.18335499 0.9712447  0.65774262
 0.58551518 0.07254361]
rand :
 [[0.98886724 0.27470265 0.86985346 0.69596657]
 [0.39366931 0.15766929 0.73751404 0.76760804]
 [0.93543212 0.61649699 0.83084235 0.74433715]]
randint :
 [85 36 18  3  3 83 82 37 38 30 73 68 90 43  4 71 55 30 77 28]
permutation :
 [ 7 10  1 11  0  2 13  4 15 14 17 18  9 19 16  5  6  3  8 12]


# Reference
<HR>
    
* https://www.kaggle.com/abdullahsahin/numpy-tutorial-for-beginner - NumPy Tutorial For Beginner
    